name: flutter_youtube
description: "Flutter package to play Youtube videos using the InAppWebView plugin."
version: 1.0.0
# repository: https://github.com/NijatNaghiyev/flutter_vimeo

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
